<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AwesomeAssertions" />
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit.v3" />
		<PackageReference Include="xunit.runner.visualstudio" />
		<PackageReference Include="bunit" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PanoramicData.Maps\PanoramicData.Maps.csproj" />
		<ProjectReference Include="..\PanoramicData.Maps.Blazor\PanoramicData.Maps.Blazor.csproj" />
	</ItemGroup>


	<ItemGroup>
		<None Include="TestData\**" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
